# .github/workflows/auto-merge.yml
name: Dependabot Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Automatic Rebase
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'labeled' }}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'rebase'
            });

      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "dependencies, automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
