name: Code Review Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ] 

jobs:
  coding-standards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm install

      - name: Echo SonarQube Host URL
        run: echo "${{ secrets.SONAR_HOST_URL }}" | sed 's/https:\/\/\(.*\)\.io/https:\/\/\*\*\*\*.\1.io/'

      - name: Run linter
        run: npm run lint

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Make sure this matches the version used in other jobs
      
      - name: Install dependencies
        run: npm install

      - name: Code Quality Analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: './'
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

  security-scan:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  
    - name: Install dependencies
      run: npm install
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

