name: Dependency Update Workflow

on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch: 
jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Use Dependabot for dependency updates
        id: dependabot
        uses: dependabot/fetch-metadata@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dependency-type: 'direct:production'
          update-types: 'version-update:semver-major'

      - name: Create Pull Request for updates
        if: steps.dependabot.outputs.updates-available == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update dependencies
          title: '[Dependabot] Dependency update'
          body: |
            Updates dependencies to the latest versions.
            Please review the changes and merge if appropriate.
          branch: feature/dependency-updates
          delete-branch: true
          labels: dependencies, automated pr
