name: Dependency-Updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      dependabot_version:
        description: 'Dependabot version to use'
        default: '0.117.x'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Run Dependabot
        uses: dependabot/dependabot-core@${{ inputs.dependabot_version }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"
          package-ecosystem: "npm"
          schedule: "daily"
          versioning-strategy: "increase"
          open-pull-requests-limit: 10
