name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs

    - name: Build documentation
      run: mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site

    - name: Log deployment message
      if: github.event_name == 'push'
      run: echo "Documentation has been updated! View the live version here: https://muhammadtaimooranwar511.github.io/SCD_THEORY_ASG02/"

  comment-pr:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'pull_request'
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Documentation has been updated! View the live version [here](https://muhammadtaimooranwar511.github.io/SCD_THEORY_ASG02/)."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
